# Generated by Django 4.2.7 on 2026-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
