# Generated by Django 4.2.7 on 2026-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_add_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="upazila",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cox's Bazar Sadar", "Cox's Bazar Sadar"),
                    ("Teknaf", "Teknaf"),
                    ("Ukhiya", "Ukhiya"),
                    ("Chakaria", "Chakaria"),
                    ("Ramu", "Ramu"),
                    ("Pekua", "Pekua"),
                    ("Maheshkhali", "Maheshkhali"),
                    ("Kutubdia", "Kutubdia"),
                    ("Eidgaon", "Eidgaon"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
